#!/bin/bash



git_version=$(git describe HEAD --tags --abbrev=4)


if [ ${SOURCE_BRANCH} == "master" ]
then
    version=$git_version
else
    version=$(echo ${SOURCE_BRANCH} | sed 's/v//')
fi

cat << EOF > puppetboard/version.py
#
# Puppetboard version module
#
__version__ = '${version}'
EOF

